name: Build and Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          cd scr/CashCat/cashcat_project
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd scr/CashCat/cashcat_project/cashcat
          pytest tests.py
      - name: Build Docker image
        run: |
          cd scr/CashCat/cashcat_project
          docker build -t anhmeo/group-d:latest -f Dockerfile .
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push anhmeo/group-d:latest
