name: Build and Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        working-directory: scr/CashCat/cashcat_project
        run: |
          pip install -r requirements.txt
      - name: Run tests
        continue-on-error: true 
        working-directory: scr/CashCat/cashcat_project/cashcat
        run: |
          pytest tests.py
      - name: Build Docker image
        continue-on-error: true
        working-directory: scr/CashCat/cashcat_project
        run: |
          docker build -t anhmeo/group-d:latest -f Dockerfile .
      - name: Log in to Docker Hub
        continue-on-error: true
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        continue-on-error: true
        run: |
          docker push anhmeo/group-d:latest
