name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ASIAW3MD7TU2LS6IMPE2
          AWS_SECRET_ACCESS_KEY: fCbHStY6B9lFixCDyxUF9SNvx8f7/GO4Bqo9HhPK
        run: terraform apply -auto-approve
      - name: Deploy to EC2
        env:
            EC2_PUBLIC_IP: "52.35.13.102"
        run: |
          docker pull whansen340/task-management-api:latest
          ssh -o StrictHostKeyChecking=no -i SHA256:yIIhcupZWY8XD4isRZpkj1r7Wyp2pLQ0uhaOEIqf59k ec2-user@52.35.13.102 << 'EOF'
            docker stop task-api || true
            docker rm task-api || true
            docker run -d --name task-api -p 80:3000 whansen340/task-management-api:latest
          EOF